import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import { TeamProfilePage } from "./TeamProfilePage";
import { OpponentComparisonPage } from "./OpponentComparisonPage";
import { PreMatchBriefingPage } from "./PreMatchBriefingPage";
import { PreMatchBriefingPrintPage } from "./PreMatchBriefingPrintPage";
import { EventMatchWorkspacePage } from "./EventMatchWorkspacePage";
import { LiveMatchesPage } from "./LiveMatchesPage";
import { FootballHomePage } from "./FootballHomePage";
import { MatchupPreviewPage } from "./MatchupPreviewPage";
import "./styles.css";
const teamMatch = window.location.pathname.match(/^\/teams\/([^/]+)\/?$/);
const eventMatch = window.location.pathname.match(/^\/event-matches\/([^/]+)\/([^/]+)\/([^/]+)\/([^/]+)\/([^/]+)(?:\/(overview|flow|teams|goals|evidence))?\/?$/);
const opponentComparison = /^\/opponent-comparison\/?$/.test(window.location.pathname);
const preMatchBriefing = /^\/pre-match-briefing\/?$/.test(window.location.pathname);
const preMatchBriefingPrint = /^\/pre-match-briefing\/print\/?$/.test(window.location.pathname);
const liveMatches = /^\/live\/?$/.test(window.location.pathname);
const analysisMatch = /^\/matches\/[^/]+(?:\/(?:overview|story|flow|teams|goals|evidence))?\/?$/.test(window.location.pathname);
const footballDataPreview = window.location.pathname.match(/^\/matchup-preview\/football-data\/(\d+)\/?$/);
const matchupPreview = window.location.pathname.match(/^\/matchup-preview\/(\d+)\/?$/);
createRoot(document.getElementById("root")!).render(<StrictMode>{footballDataPreview ? <MatchupPreviewPage fixtureId={Number(footballDataPreview[1])} provider="football-data"/> : matchupPreview ? <MatchupPreviewPage fixtureId={Number(matchupPreview[1])}/> : liveMatches ? <LiveMatchesPage /> : eventMatch ? <EventMatchWorkspacePage provider={decodeURIComponent(eventMatch[1])} teamId={decodeURIComponent(eventMatch[2])} competitionId={decodeURIComponent(eventMatch[3])} seasonId={decodeURIComponent(eventMatch[4])} matchId={decodeURIComponent(eventMatch[5])} section={(eventMatch[6] as "overview" | "flow" | "teams" | "goals" | "evidence" | undefined) ?? "overview"}/> : preMatchBriefingPrint ? <PreMatchBriefingPrintPage /> : preMatchBriefing ? <PreMatchBriefingPage /> : opponentComparison ? <OpponentComparisonPage /> : teamMatch ? <TeamProfilePage teamId={decodeURIComponent(teamMatch[1])} /> : analysisMatch ? <App /> : <FootballHomePage />}</StrictMode>);
