import type { FindingDetailResponse, FindingExplanationResponse, MatchSummaryResponse, PitchFrameResponse, RankedFindingsResponse } from "./types";

const moments = [{ frame: 3906, period: 1, timestamp: "00:02:19.60", elapsed_seconds: 139.6, phase_frame_start: 3906, phase_frame_end: 4081 }];
const priority = { evidence_strength: .85, sample_adequacy: 1, effect_magnitude: 1, temporal_relevance: .65, data_quality_coverage: 1, redundancy_penalty: 0, priority_score: .917, comparator: { type: "within_team_phase_median_dimension", value_metres: 29.4, dispersion_metres: 12.6, relative_dispersion: .43 }, suppressed_as_duplicate: false, redundancy_group: "868:phase_shape:in_possession" };
const coverage = [
  { analysis: "team_shape", supported: true, status: "run" as const, reason: "", finding_count: 4 },
  { analysis: "phase_shape_analysis", supported: true, status: "run" as const, reason: "", finding_count: 27 },
  { analysis: "local_defensive_context", supported: true, status: "run" as const, reason: "", finding_count: 0 },
  { analysis: "temporal_shot_analysis", supported: true, status: "run" as const, reason: "", finding_count: 2 },
  { analysis: "ball_goal_geometry", supported: true, status: "available_not_implemented" as const, reason: "", finding_count: 0 }
];
const finding = { rank: 1, finding_id: "2017461:868:phase_shape:in_possession:create", match_id: 2017461, team_id: 868, finding_type: "phase_shape_variability", title: "MEL variable create shape", description: "Native outfield shape varied within create: width IQR 12.6 m and length IQR 9.1 m across 18 intervals.", sample_size: 1573, confidence_level: "descriptive_moderate", selection_reason: "top_phase_shape", priority, limitations: ["Phase labels are provider supplied; variation is descriptive and does not identify a cause or prescribe a response."] };

export const mockSummary: MatchSummaryResponse = { schema_version: "v1", match: { match_id: 2017461, provider: "skillcorner_open_data", pitch_length_m: 105, pitch_width_m: 68, date_time: "2025-05-17T09:35:00Z", home_team: { team_id: 868, name: "Melbourne Victory Football Club", code: "MEL", score: 0 }, away_team: { team_id: 4177, name: "Auckland FC", code: "AUC", score: 2 } }, capabilities: { has_continuous_tracking: true, has_ball_tracking: true, has_verified_roles: true, has_attacking_direction: true, has_events: true, has_tactical_phases: true, has_assumed_roles: false }, finding_count: 33, shortlist_count: 5, warnings: [], analysis_coverage: coverage };
export const mockRanked: RankedFindingsResponse = { schema_version: "v1", ranked_findings: [finding, { ...finding, rank: 2, finding_id: "2017461:4177:shape_extreme:outfield_length", team_id: 4177, title: "Auckland FC outfield length: typical and more extended shapes", finding_type: "team_shape_extreme", description: "Auckland FC's median outfield length was 31.0 m. In a high-tail episode it reached 51.4 m, 20.4 m from the median.", priority: { ...priority, priority_score: .891 } }] };
export const mockDetail: FindingDetailResponse = { schema_version: "v1", finding, evidence: { exact_metrics: { width_iqr_metres: 12.6, length_iqr_metres: 9.1, median_width_metres: 34.2, median_length_metres: 29.4, phase_intervals: 18 }, comparator: priority.comparator, supporting_references: moments, representative_moments: moments, capability_provenance: { provider: "skillcorner_open_data", capabilities: mockSummary.capabilities, required_capabilities: ["has_continuous_tracking", "has_verified_roles", "has_tactical_phases"], allow_assumed_roles: false }, coverage: { analysis_coverage: coverage, finding_sample_size: 1573, reference_count: 1 }, limitations: finding.limitations } };
export const mockExplanation: FindingExplanationResponse = { schema_version: "v1", finding_id: finding.finding_id, explanation: { plain_english_summary: "Melbourne's outfield width varied across its chance-creation phases.", why_it_matters: "This may reflect different spacing structures as attacks developed.", what_to_review_in_video: "At frame 3906, review the spacing between Melbourne's widest outfield players.", confidence_note: "This is descriptive evidence from 18 phase intervals and does not establish tactical quality or causation." }, metadata: { evidence_hash: "mock-evidence-hash", prompt_version: "tactiq-finding-explanation-v1", model_id: "mock-model", source: "model", cache_hit: false, validation_warnings: [] } };
export const mockFrame: PitchFrameResponse = { schema_version: "v1", match_id: 2017461, frame: 3906, period: 1, timestamp: "00:02:19.60", elapsed_seconds: 139.6, pitch: { length_m: 105, width_m: 68 }, players: Array.from({ length: 20 }, (_, index) => ({ player_id: index + 1, team_id: index < 10 ? 868 : 4177, team_acronym: index < 10 ? "MEL" : "AUC", position: index % 10 === 0 ? "Goalkeeper" : "Outfield", x: -45 + ((index * 13) % 88), y: -26 + ((index * 17) % 52), is_detected: true })), ball: { x: 5.1, y: -4.2, is_observed: true } };
